### ISSUE TITLE
Upgrade to 0.28

### ISSUE THREAD

**Issue by furilo** [decidim-ice/decidim-module-decidim_awesome#251]
Issue to track the upgrade to the 0.28 version, which will be released shortly. We ([Populate](https://github.com/populateTools/)) will contribute to the effort, and invite anyone who has time to do it, as the effort is considerable ;) 

- The idea is to send a PR for each feature as outlined below. 
- If anyone plans to work a feature please add your name in the corresponding line, so we can keep track. 
- We may open issues for each feature if discussion/support is needed, since doing all here may be cumbersome.
- Since we have been working in the redesign process, we are open to try to help with technical issues that may arise in the process for those who contribute to the effort
- We have also created a Telegram group to have a place to comment technical - feel free to join https://t.me/+8nhIyJCI2sg3MWM0

### Doing 

- [ ] **Populate** 7. Fullscreen Iframe component

### ToDo

- [ ] 1. Image support for the Quill editor
- [ ] 2. Auto-save for surveys and forms
- [ ] 3. Images in proposals
- [ ] 4. Markdown editor for proposals
- [ ] 5. Admin scope configuration
- [ ] 6. Awesome map component
- [ ] 8. Live support chat
- [ ] 9. Custom CSS applied only according scoped restrictions
- [ ] 10. Change the main menu of Decidim entirely!
- [ ] 11. Assign admins to specific scopes and prevent them modify anything else
- [ ] 12. Custom fields for proposals
- [ ] 13. Custom Redirections (or URL shortener feature)
- [ ] 14. Custom validation rules for title and body in proposals
- [ ] 15. Admin accountability
- [ ] 16. Additional proposal sortings
- [ ] 17. Weighted voting

**Comment by microstudi** [comment]
When the first PR dedicated to the upgrade is merged, we will create a PR from `develop` to `main` with this checklist. When fulfilled, version 0.11 will be released.

**Comment by froger** [comment]
Hi, at Octree we can help. I know quiet well the code for `12. Custom fields for proposals`. I can stay accountable to help upgrading this.

**Comment by aramollis** [comment]
> Hi, at Octree we can help. I know quiet well the code for `12. Custom fields for proposals`. I can stay accountable to upgrade this.

Any updates on this @froger ? 😉

**Comment by paarals** [comment]
> > Hi, at Octree we can help. I know quiet well the code for `12. Custom fields for proposals`. I can stay accountable to upgrade this.
> 
> Any updates on this @froger ? 😉

hi @aramollis, this feature is almost done. you can see better the execution of the upgrade here: https://github.com/decidim-ice/decidim-module-decidim_awesome/pull/270. as long as we see that no one is taking any issue, we will love if people can test and report any bugs here: https://decidim-awesome.dev.pokecode.net/

**Comment by microstudi** [comment]
> > > Hi, at Octree we can help. I know quiet well the code for `12. Custom fields for proposals`. I can stay accountable to upgrade this.
> > 
> > 
> > Any updates on this @froger ? 😉
> 
> hi @aramollis, this feature is almost done. you can see better the execution of the upgrade here: #270. as long as we see that no one is taking any issue, we will love if people can test and report any bugs here: https://decidim-awesome.dev.pokecode.net/

Particularly, I'm almost finished the custom fields in this PR #277

**Comment by aramollis** [comment]
> we will love if people can test and report any bugs here: https://decidim-awesome.dev.pokecode.net/

Not so much to test with a regular user (In front I see only a accessibility issue with colors of the "cards map"). You can make me admin to test a little more.

**Comment by microstudi** [comment]
@aramollis you got it!

**Comment by aramollis** [comment]
> @aramollis you got it!

Seems my user is downgraded again as regular user. I found a possible bug with custom fields of Awesome module. 
Can you give me admin rights again to check? @microstudi @paarals

**Comment by aramollis** [comment]
> I found a possible bug with custom fields of Awesome module. 

Seems is working as expected in this [site](https://decidim-awesome.dev.pokecode.net/admin/participatory_processes/pressupost-participatiu/components/1/manage/proposals/new?locale=ca) with custom fields in proposals. Then something to fix in our site maybe update to the last version avaialable. Tx!

**Comment by aramollis** [comment]
Any plans to finish issues & release 11 version (0.28 ready)?
Maybe we can check pending issues & try to fix them.

> ToDo
>  12. Custom fields for proposals

- [ ] https://github.com/decidim-ice/decidim-module-decidim_awesome/issues/290
- [ ] https://github.com/decidim-ice/decidim-module-decidim_awesome/issues/288

@froger You said you can contribute to this feature? Can you fix these pending issues?
Any other issue to fix? @microstudi
