### ISSUE TITLE
10. Change the main menu of Decidim entirely!

### ISSUE THREAD

**Issue by paarals** [decidim-ice/decidim-module-decidim_awesome#271]
**Current implementation**
In version 0.27 and earlier, there is only one main menu. The functionalities that could be used were:
1. Add a new item in the menu, define a position, decide if it opens in the same window and the visibility depending on the type of user. 
2. The levels created by default allows to modify the name of the level, to define a new position, to decide if it opens in the same window and the visibility depending on the type of user. 

Example (comunitat.canodrom.barcelona): 
![imatge](https://github.com/decidim-ice/decidim-module-decidim_awesome/assets/40388743/512cadf0-da68-427a-9765-167e37de883a)

In version 0.28, we have two menus. The main menu and the home page menu (content block). It should be possible to ensure the same functionality as before. 

Main menu(nightly.decidim.org):
![imatge](https://github.com/decidim-ice/decidim-module-decidim_awesome/assets/40388743/77490cae-8079-454f-9a08-3c16975a1594)

Content block menu:
![imatge](https://github.com/decidim-ice/decidim-module-decidim_awesome/assets/40388743/ea323ff3-cc5e-4f5e-9da4-b5888e3ed518)

**Tasks**

Use: https://decidim-awesome.dev.pokecode.net

Main menu (any level)
- [x] Add/Remove item
- [x] Modify position 
- [x] Modify visibility 
- [x] Allow to open in the same window or in another window

Menu content block start page (any level)
- [x] Add/Remove item
- [x] Modify position 
- [x] Modify visibility 
- [x] Allow to open in the same window or in another window

**Comment by paarals** [comment]
tested via @paarals
